version: '3'

services:

  db-service:
    image: postgres:11.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./:/docker-entrypoint-initdb.d

  cache-service:
    image: redis:5.0
    ports:
      - "6379:6379"

  auzmor-sms-service:
    image: sabirhussain79/sms-service:v1.0.1
    ports:
      - "8080:8080"
    links:
      - "db-service:auzmordbserver"
      - "cache-service:auzmorcacheserver"
